# See https://github.com/actions/starter-workflows/blob/1dd15d20337289b85cecafdde824b3a44bc8ed27/ci/ruby.yml
# which was used as a reference
name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install apt deps
        run: |
          sudo apt-get update
          sudo apt-get install cmake libevent-dev curl ruby valgrind clang gcc build-essential
      - name: Install gem deps
        run: bundle install
      - name: Compile
        run: make
      - name: Run tests
        run: bundle exec make test
